- judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/FunctionsTest.java
- judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/OperatorsTest.java
- judo-runtime-core-jsl-itest/src/test/resources/model/Functions.jsl
- judo-runtime-core-jsl-itest/src/test/resources/model/Operators.jsl
- pom.xml
<table>
<td>
<a href="https://blackbelt.atlassian.net/browse/JNG-4140" title="JNG-4140" target="_blank"><img alt="Story" src="https://blackbelt.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />JNG-4140</a>  Extend JSL/JQL functions
</td></table>
<br />
> JNG-4140 Extend JSL-JQL functions

- judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/FunctionsTest.java
- judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/PrimitivesTest.java
- judo-runtime-core-jsl-itest/src/test/resources/model/Functions.jsl
- judo-runtime-core-jsl-itest/src/test/resources/model/Primitives.jsl
- pom.xml
<table>
<td>
<a href="https://blackbelt.atlassian.net/browse/JNG-4149" title="JNG-4149" target="_blank"><img alt="Story" src="https://blackbelt.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />JNG-4149</a>  Fixing call function from Literal value and Parenthized expression
</td></table>
<br />
> JNG-4149 Fixing parentheses expression function call and kleene tests added

- judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/FunctionsTest.java
- judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/OperatorsTest.java
- judo-runtime-core-jsl-itest/src/test/resources/model/Functions.jsl
- judo-runtime-core-jsl-itest/src/test/resources/model/Operators.jsl
- pom.xml
<table>
<td>
<a href="https://blackbelt.atlassian.net/browse/JNG-4151" title="JNG-4151" target="_blank"><img alt="Story" src="https://blackbelt.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />JNG-4151</a>  Support isDefined() function on any kind of expression
</td></table>
<br />
> JNG-4151 isDefined on all expressions

- judo-runtime-core-jsl-itest/pom.xml
- judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/FunctionsTest.java
- judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/OperatorsTest.java
- judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/PrimitivesTest.java
- judo-runtime-core-jsl-itest/src/test/resources/model/Functions.jsl
- judo-runtime-core-jsl-itest/src/test/resources/model/Operators.jsl
- judo-runtime-core-jsl-itest/src/test/resources/model/Primitives.jsl
<table>
<td>
<a href="https://blackbelt.atlassian.net/browse/JNG-4003" title="JNG-4003" target="_blank"><img alt="Task" src="https://blackbelt.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10318?size=medium" />JNG-4003</a>  Add validator tests to JSL tests
</td></table>
<br />
> JNG-4003 add missing type tests

- pom.xml
<table>
<td>
<a href="https://blackbelt.atlassian.net/browse/JNG-3987" title="JNG-3987" target="_blank"><img alt="Bug" src="https://blackbelt.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />JNG-3987</a>  Assigning value to time typed attribute fails with SQL exception
</td></table>
<br />
> JNG-3987 Fix time constant

- judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/FunctionsTest.java
- judo-runtime-core-jsl-itest/src/test/resources/model/Functions.jsl
- pom.xml
<table>
<td>
<a href="https://blackbelt.atlassian.net/browse/JNG-4169" title="JNG-4169" target="_blank"><img alt="Bug" src="https://blackbelt.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />JNG-4169</a>  Non exact like function throws compile error
</td></table>
<br />
JNG-4169 Support ilike in JSl
> JNG-4169 Support ilike in JSl

- judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/FunctionsTest.java
- pom.xml
<table>
<td>
<a href="https://blackbelt.atlassian.net/browse/JNG-3900" title="JNG-3900" target="_blank"><img alt="Bug" src="https://blackbelt.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />JNG-3900</a>  Time.asString() returns wrong output
</td></table>
<br />
> JNG-3900 fix time asString

- judo-runtime-core-jsl-itest/pom.xml
- judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/PrimitivesTest.java
- judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/QueryTest.java
- judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/SalesModelTest.java
- judo-runtime-core-jsl-itest/src/test/resources/model/Abstract.jsl
- judo-runtime-core-jsl-spring-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/spring/JudoRuntimeCoreSpringApplicationTests.java
- pom.xml
<table>
<td>
<a href="https://blackbelt.atlassian.net/browse/JNG-4188" title="JNG-4188" target="_blank"><img alt="Task" src="https://blackbelt.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10318?size=medium" />JNG-4188</a>  Create method should not be generated for on abstract entities
</td></table>
<br />
JNG-4188 Create method should not be generated for on abstract entities
> JNG-4188 Create method should not be generated for on abstract entities

- judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/CompositionRelationshipsTest.java
- judo-runtime-core-jsl-spring-itest/pom.xml
- judo-runtime-core-jsl-spring-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/spring/JudoRuntimeCoreSpringApplicationTests.java
- pom.xml
<table>
<td>
<a href="https://blackbelt.atlassian.net/browse/JNG-3861" title="JNG-3861" target="_blank"><img alt="Story" src="https://blackbelt.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />JNG-3861</a>  Transaction support for SDK with JSL DSL
</td></table>
<br />
JNG-3861 Using Spring PlatformTransactionManager
> JNG-3861 Using Spring PlatformTransactionManager

- judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/PrimitiveFunctionsTest.java
- judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/QueryTest.java
- judo-runtime-core-jsl-itest/src/test/resources/model/QueryModel.jsl
- judo-runtime-core-jsl-spring-itest/src/main/resources/model/SalesModel.jsl
- judo-runtime-core-jsl-spring-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/spring/JudoRuntimeCoreSpringApplicationTests.java
- pom.xml
<table>
<td>
<a href="https://blackbelt.atlassian.net/browse/JNG-4196" title="JNG-4196" target="_blank"><img alt="Bug" src="https://blackbelt.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />JNG-4196</a>  Dao implementations are not provided in Guice modules for static queries
</td></table>
<br />
> JNG-4196 support static queries for sdk

- judo-runtime-core-jsl-itest/src/test/resources/model/Primitives.jsl
- pom.xml
<table>
<td>
<a href="https://blackbelt.atlassian.net/browse/JNG-4212" title="JNG-4212" target="_blank"><img alt="Bug" src="https://blackbelt.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />JNG-4212</a>  import judo types throws error
</td></table>
<br />
JNG-4212 Wrong judo types import
> JNG-4212 Wrong judo types import

- pom.xml
<table>
<td>
<a href="https://blackbelt.atlassian.net/browse/JNG-4032" title="JNG-4032" target="_blank"><img alt="Story" src="https://blackbelt.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />JNG-4032</a>  Default value of query arguments should not be required
</td></table>
<br />
JNG-4032 Query input parameter default value removed
> JNG-4032 Query input parameter default value removed

- judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/FunctionsTest.java
- judo-runtime-core-jsl-itest/src/test/resources/model/Functions.jsl
- pom.xml
<table>
<td>
<a href="https://blackbelt.atlassian.net/browse/JNG-4078" title="JNG-4078" target="_blank"><img alt="Story" src="https://blackbelt.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />JNG-4078</a>  orElse() for all types
</td></table>
<br />
> JNG-4078 orElse for all types tests

- judo-runtime-core-jsl-itest/src/test/resources/model/Functions.jsl
- pom.xml
<table>
<td>
<a href="https://blackbelt.atlassian.net/browse/JNG-3909" title="JNG-3909" target="_blank"><img alt="Bug" src="https://blackbelt.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />JNG-3909</a>  Extending imported class causes transformation error
</td></table>
<br />
JNG-3909 Fixing extend with default value
> JNG-3909 Fixing extend with default value

- judo-runtime-core-jsl-itest/src/test/resources/model/Functions.jsl
- pom.xml
<table>
<td>
<a href="https://blackbelt.atlassian.net/browse/JNG-3896" title="JNG-3896" target="_blank"><img alt="Bug" src="https://blackbelt.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />JNG-3896</a>  Derived on inherited field navigation throws transformation error
</td></table>
<br />
JNG-3896 Fixing duplicate Xmiid error
> JNG-3896 Fixing duplicate Xmiid error

- judo-runtime-core-jsl-itest/pom.xml
- judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/ContainsTest.java
- judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/FunctionsTest.java
- judo-runtime-core-jsl-itest/src/test/resources/model/ContainsTest.jsl
- judo-runtime-core-jsl-itest/src/test/resources/model/Functions.jsl
- pom.xml
<table>
<td>
<a href="https://blackbelt.atlassian.net/browse/JNG-4174" title="JNG-4174" target="_blank"><img alt="Bug" src="https://blackbelt.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />JNG-4174</a>  Building SDK with !contains() expression throws Injector error
</td></table>
<br />
JNG-4174_Fix_contains
> JNG-4174 Fix contains

- judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/OperatorsTest.java
- judo-runtime-core-jsl-itest/src/test/resources/model/Functions.jsl
- judo-runtime-core-jsl-itest/src/test/resources/model/Operators.jsl
- pom.xml
<table>
<td>
<a href="https://blackbelt.atlassian.net/browse/JNG-4243" title="JNG-4243" target="_blank"><img alt="Story" src="https://blackbelt.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />JNG-4243</a>  plus/minus literal numbers
</td></table>
<br />
JNG-4243 plus and minus literal numbers
> JNG-4243 plus and minus literal numbers

- judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/FunctionsTest.java
- judo-runtime-core-jsl-itest/src/test/resources/model/Functions.jsl
- pom.xml
<table>
<td>
<a href="https://blackbelt.atlassian.net/browse/JNG-4197" title="JNG-4197" target="_blank"><img alt="Bug" src="https://blackbelt.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />JNG-4197</a>  Function calls for navigations cause parser errors
</td></table>
<br />
JNG-4197 Fix navigation after function call
> JNG-4197 Fix navigation after function call

- judo-runtime-core-jsl-spring-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/spring/JudoRuntimeCoreSpringApplicationTests.java
<table>
<td>
<a href="https://blackbelt.atlassian.net/browse/JNG-3825" title="JNG-3825" target="_blank"><img alt="Task" src="https://blackbelt.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10318?size=medium" />JNG-3825</a>  Test Transaction Manager in Spring SDK
</td></table>
<br />
> JNG-3825 Spring transactional tests

- pom.xml
<table>
<td>
<a href="https://blackbelt.atlassian.net/browse/JNG-4213" title="JNG-4213" target="_blank"><img alt="Story" src="https://blackbelt.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />JNG-4213</a>  Add offset support to DAO
</td></table>
<br />
JNG-4213 Add Offset support for DAO / Query / REST
> JNG-4213 Add Offset support for DAO / Query / REST

- pom.xml
<table>
<td>
<a href="https://blackbelt.atlassian.net/browse/JNG-4234" title="JNG-4234" target="_blank"><img alt="Story" src="https://blackbelt.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />JNG-4234</a>  Add count and totalCount support for DAO / SDK / Rest
</td></table>
<br />
JNG-4234 Add query count support for DAO / SDK / Rest
> JNG-4234 Add query count support for DAO / SDK / Rest

- judo-runtime-core-jsl-itest/pom.xml
- judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/CastingFunctionsTest.java
- judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/FunctionsTest.java
- judo-runtime-core-jsl-itest/src/test/resources/model/CastingFunctionsModel.jsl
- judo-runtime-core-jsl-itest/src/test/resources/model/Functions.jsl
- pom.xml
<table>
<td>
<a href="https://blackbelt.atlassian.net/browse/JNG-4181" title="JNG-4181" target="_blank"><img alt="Story" src="https://blackbelt.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />JNG-4181</a>  Extend asType() implementation
</td></table>
<br />
> JNG-4181 Fix astype

- judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/AssociationRelationshipsTest.java
- judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/CompositionRelationshipsTest.java
- judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/PrimitivesTest.java
- judo-runtime-core-jsl-itest/src/test/resources/model/AssociationRelationships.jsl
- judo-runtime-core-jsl-itest/src/test/resources/model/CompositionRelationships.jsl
<table>
<td>
<a href="https://blackbelt.atlassian.net/browse/JNG-3755" title="JNG-3755" target="_blank"><img alt="Sub-task" src="https://blackbelt.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10316?size=medium" />JNG-3755</a>  Entity validation extended
</td></table>
<br />
> JNG-3755 additional tests

- judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/FunctionsTest.java
- judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/PrimitivesTest.java
- pom.xml
<table>
<td>
<a href="https://blackbelt.atlassian.net/browse/JNG-4290" title="JNG-4290" target="_blank"><img alt="Bug" src="https://blackbelt.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />JNG-4290</a>  asString function on boolean attributes returns different casing result in HSQL vs PSQL
</td></table>
<br />
JNG-4290 Lowercase boolean string
> JNG-4290 Lowercase boolean string

- pom.xml
<table>
<td>
<a href="https://blackbelt.atlassian.net/browse/JNG-3992" title="JNG-3992" target="_blank"><img alt="Bug" src="https://blackbelt.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />JNG-3992</a>  Filtering for string contained in email displays error
</td></table>
<br />
JNG-3992 Fix email filter
> JNG-3992 Fix email filter

- judo-runtime-core-bootstrap-jsl/src/test/resources/models/sample.jsl
- judo-runtime-core-jsl-itest/src/test/resources/model/ContainerDerived.jsl
- judo-runtime-core-jsl-itest/src/test/resources/model/ContainsTest.jsl
- judo-runtime-core-jsl-itest/src/test/resources/model/Functions.jsl
- judo-runtime-core-jsl-itest/src/test/resources/model/Primitives.jsl
- judo-runtime-core-jsl-itest/src/test/resources/model/QueryModel.jsl
- judo-runtime-core-jsl-itest/src/test/resources/model/SalesModel.jsl
- judo-runtime-core-jsl-itest/src/test/resources/model/sample.jsl
- judo-runtime-core-jsl-spring-itest/src/main/resources/model/SalesModel.jsl
- pom.xml
<table>
<td>
<a href="https://blackbelt.atlassian.net/browse/JNG-3500" title="JNG-3500" target="_blank"><img alt="Task" src="https://blackbelt.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10318?size=medium" />JNG-3500</a>  JSL Semantic Validation
</td></table>
<br />
JNG-3500 JSL semantic validation
> JNG-3500 JSL semantic validation
